// <auto-generated />
using System;
using LMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Migrations
{
    [DbContext(typeof(LmsContext))]
    [Migration("20260504050455_Second_Status_Add")]
    partial class Second_Status_Add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            DueDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPoints = 10,
                            Title = "Variables Assignment"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            DueDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPoints = 25,
                            Title = "Linked List"
                        });
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseFee")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InstructorId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxEnrollment")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("InstructorId1");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseFee = 0,
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3917),
                            Credits = 3,
                            Description = "Basics of coding",
                            EndDate = new DateTime(2026, 9, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3908),
                            InstructorId = "I1",
                            MaxEnrollment = 30,
                            StartDate = new DateTime(2026, 5, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3894),
                            Title = "Introduction to Programming"
                        },
                        new
                        {
                            Id = 2,
                            CourseFee = 0,
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3926),
                            Credits = 3,
                            Description = "Advanced data handling",
                            EndDate = new DateTime(2026, 9, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3926),
                            InstructorId = "I2",
                            MaxEnrollment = 25,
                            StartDate = new DateTime(2026, 5, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3925),
                            Title = "Data Structures"
                        },
                        new
                        {
                            Id = 3,
                            CourseFee = 0,
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3952),
                            Credits = 3,
                            Description = "ASP.NET Core",
                            EndDate = new DateTime(2026, 9, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3951),
                            InstructorId = "I3",
                            MaxEnrollment = 20,
                            StartDate = new DateTime(2026, 5, 4, 11, 4, 52, 783, DateTimeKind.Local).AddTicks(3942),
                            Title = "Web Development"
                        });
                });

            modelBuilder.Entity("LMS.Models.StudentAssignment", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PointsEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "AssignmentId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("StudentAssignments");

                    b.HasData(
                        new
                        {
                            StudentId = "S1",
                            AssignmentId = 1,
                            Feedback = "Good work",
                            PointsEarned = 8m,
                            Status = 3
                        },
                        new
                        {
                            StudentId = "S2",
                            AssignmentId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("LMS.Models.StudentCourse", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = "S1",
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            StudentId = "S2",
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            StudentId = "S3",
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            StudentId = "S4",
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            StudentId = "S5",
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("LMS.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "I1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f5643581-fea0-412d-8d90-911f38795051",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 180, DateTimeKind.Local).AddTicks(441),
                            Email = "smith@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Smith",
                            NormalizedEmail = "SMITH@UNI.COM",
                            NormalizedUserName = "SMITH@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECtzquudIwisefPVzlupR1EjoYqqQdOw+UmUYuzdo/G/w3bSmdiSCahX22KmNlOPDQ==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "6eceef2d-63da-405f-9920-27c7500b1713",
                            TwoFactorEnabled = false,
                            UserName = "smith@uni.com"
                        },
                        new
                        {
                            Id = "I2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e09558c6-0465-4794-ba0a-84b602d9aff0",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 230, DateTimeKind.Local).AddTicks(8074),
                            Email = "johnson@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Johnson",
                            NormalizedEmail = "JOHNSON@UNI.COM",
                            NormalizedUserName = "JOHNSON@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO8MSGnOiclCGN12+PI3IkkP3kYATIUn0i2jEttK8HnUaP8d6+77n2j/nUALfAuE5w==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "d5c6a22c-8f47-4630-81e4-d8519836de6c",
                            TwoFactorEnabled = false,
                            UserName = "johnson@uni.com"
                        },
                        new
                        {
                            Id = "I3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8e37f67-d264-489b-af51-fb6418e79420",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 280, DateTimeKind.Local).AddTicks(9289),
                            Email = "lee@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Lee",
                            NormalizedEmail = "LEE@UNI.COM",
                            NormalizedUserName = "LEE@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDOMhzTQAmaHe27l7E4Ws7StWvosjc7p5qvQ1pMdD93MLkDIGFf2HA9kzVosmf2FdQ==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "5c6d3349-e175-4ec3-961a-bcdf4c8500ed",
                            TwoFactorEnabled = false,
                            UserName = "lee@uni.com"
                        },
                        new
                        {
                            Id = "S1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdeb8816-2af9-40c9-90b1-b2ddc524c024",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 333, DateTimeKind.Local).AddTicks(1674),
                            Email = "student1@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 1",
                            NormalizedEmail = "STUDENT1@UNI.COM",
                            NormalizedUserName = "STUDENT1@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBc54ywryxsGW+QssKcC/MdI7EFgcFgKuMZ6rVU8j3j3AIEB5VkOEtuCFyCxP4hkXg==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "a1d69efd-77b2-4c58-9197-e7f190336d47",
                            TwoFactorEnabled = false,
                            UserName = "student1@uni.com"
                        },
                        new
                        {
                            Id = "S2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0a7dd97-576b-4873-bcad-f097723b599a",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 386, DateTimeKind.Local).AddTicks(2851),
                            Email = "student2@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 2",
                            NormalizedEmail = "STUDENT2@UNI.COM",
                            NormalizedUserName = "STUDENT2@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED4f1jZxMtVaAvWbLHY55MsFzoQT7gLlQxo6uQ7zaE23A3z4mroPVMMZTINdWm69ug==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "428f770b-02cf-444a-a92e-0bfe462fe5a6",
                            TwoFactorEnabled = false,
                            UserName = "student2@uni.com"
                        },
                        new
                        {
                            Id = "S3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82070186-d596-4fac-8390-464f8f70347a",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 446, DateTimeKind.Local).AddTicks(5388),
                            Email = "student3@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 3",
                            NormalizedEmail = "STUDENT3@UNI.COM",
                            NormalizedUserName = "STUDENT3@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIjwJdNsB9CqQOnp25ZMg20W6rjVTJXmxnxC53e4FN58UKvrLP7xHaNMSbB2oHuLTg==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "a24f5064-6fe1-44b5-9d4e-b899df04dcd6",
                            TwoFactorEnabled = false,
                            UserName = "student3@uni.com"
                        },
                        new
                        {
                            Id = "S4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8221ba6f-40d1-4a4d-95fe-06b1db709ff4",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 511, DateTimeKind.Local).AddTicks(7607),
                            Email = "student4@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 4",
                            NormalizedEmail = "STUDENT4@UNI.COM",
                            NormalizedUserName = "STUDENT4@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFpOp2G+gHmU9he0HKlKd81+Sl0o1MNjapqKOnGzcL43E0dIaO+ybfF4G281Pdug5w==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "07ef86c5-fad9-461b-84d9-3f0f48144551",
                            TwoFactorEnabled = false,
                            UserName = "student4@uni.com"
                        },
                        new
                        {
                            Id = "S5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2f3ed0a-c87e-4b6a-877b-9886272805ba",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 570, DateTimeKind.Local).AddTicks(244),
                            Email = "student5@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 5",
                            NormalizedEmail = "STUDENT5@UNI.COM",
                            NormalizedUserName = "STUDENT5@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF56maLk75VfEGtWcBHUcKhJFt6jmUtMIDanyyFSBvWxJWR/GiIktgEhn4cemoVZaA==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "f3a4f006-5026-4fb7-a230-37094604902e",
                            TwoFactorEnabled = false,
                            UserName = "student5@uni.com"
                        },
                        new
                        {
                            Id = "S6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "61a5e0af-3e06-4b42-bb69-ee1c509c3177",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 626, DateTimeKind.Local).AddTicks(5165),
                            Email = "student6@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 6",
                            NormalizedEmail = "STUDENT6@UNI.COM",
                            NormalizedUserName = "STUDENT6@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIVx2zsFG8+dcMpSlyyXyRy4PrfvDd63HekSd47iHZNF+RFQqKzQg4sdGOIyzjwuTw==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "37e7736e-1cf0-45f6-a7eb-48c5399b225f",
                            TwoFactorEnabled = false,
                            UserName = "student6@uni.com"
                        },
                        new
                        {
                            Id = "S7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1384f83-c2af-4778-bfe2-bba8b6c8c288",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 680, DateTimeKind.Local).AddTicks(8227),
                            Email = "student7@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 7",
                            NormalizedEmail = "STUDENT7@UNI.COM",
                            NormalizedUserName = "STUDENT7@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFb3RYxkiEcdzYvfQZd2o5/8lvStqEfkk/auc23AyzVe30G6fxjK8TOhaxQ4CxzevA==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "badff740-2c7f-4301-9b55-87a5bb4a5375",
                            TwoFactorEnabled = false,
                            UserName = "student7@uni.com"
                        },
                        new
                        {
                            Id = "S8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eeb1c2f5-f8f0-4ee7-83be-c72c99f2f34d",
                            CreatedDate = new DateTime(2026, 5, 4, 11, 4, 52, 731, DateTimeKind.Local).AddTicks(7580),
                            Email = "student8@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 8",
                            NormalizedEmail = "STUDENT8@UNI.COM",
                            NormalizedUserName = "STUDENT8@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDCMk4HlQfodztiV2lrTcbFmQKDUB2eIzJSObh/Wgcw3XtA1Ql7Z4do0PIVnsiCflQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "1770f408-dfcb-4ba1-87d3-ef09395e0233",
                            TwoFactorEnabled = false,
                            UserName = "student8@uni.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "R1",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "R2",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "I1",
                            RoleId = "R1"
                        },
                        new
                        {
                            UserId = "I2",
                            RoleId = "R1"
                        },
                        new
                        {
                            UserId = "I3",
                            RoleId = "R1"
                        },
                        new
                        {
                            UserId = "S1",
                            RoleId = "R2"
                        },
                        new
                        {
                            UserId = "S2",
                            RoleId = "R2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMS.Models.Instructor", b =>
                {
                    b.HasBaseType("LMS.Models.User");

                    b.HasDiscriminator().HasValue("Instructor");
                });

            modelBuilder.Entity("LMS.Models.Student", b =>
                {
                    b.HasBaseType("LMS.Models.User");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.HasOne("LMS.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.HasOne("LMS.Models.User", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.Models.Instructor", null)
                        .WithMany("CourseNavigationProperty")
                        .HasForeignKey("InstructorId1");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("LMS.Models.StudentAssignment", b =>
                {
                    b.HasOne("LMS.Models.Assignment", "Assignment")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", "Student")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.Models.StudentCourse", b =>
                {
                    b.HasOne("LMS.Models.Course", "Course")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.Navigation("StudentAssignments");
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("StudentEnrollments");
                });

            modelBuilder.Entity("LMS.Models.User", b =>
                {
                    b.Navigation("AssignmentSubmissions");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LMS.Models.Instructor", b =>
                {
                    b.Navigation("CourseNavigationProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
