// <auto-generated />
using System;
using LMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Migrations
{
    [DbContext(typeof(LmsContext))]
    [Migration("20260423060708_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            DueDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPoints = 10,
                            Title = "Variables Assignment"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            DueDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPoints = 25,
                            Title = "Linked List"
                        });
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InstructorId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxEnrollment")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("InstructorId1");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(4050),
                            Credits = 3,
                            Description = "Basics of coding",
                            EndDate = new DateTime(2026, 8, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(4007),
                            InstructorId = "I1",
                            MaxEnrollment = 30,
                            StartDate = new DateTime(2026, 4, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(3991),
                            Title = "Introduction to Programming"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(4062),
                            Credits = 3,
                            Description = "Advanced data handling",
                            EndDate = new DateTime(2026, 8, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(4061),
                            InstructorId = "I2",
                            MaxEnrollment = 25,
                            StartDate = new DateTime(2026, 4, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(4060),
                            Title = "Data Structures"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(4064),
                            Credits = 3,
                            Description = "ASP.NET Core",
                            EndDate = new DateTime(2026, 8, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(4064),
                            InstructorId = "I3",
                            MaxEnrollment = 20,
                            StartDate = new DateTime(2026, 4, 23, 12, 7, 6, 590, DateTimeKind.Local).AddTicks(4063),
                            Title = "Web Development"
                        });
                });

            modelBuilder.Entity("LMS.Models.StudentAssignment", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PointsEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "AssignmentId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("StudentAssignments");

                    b.HasData(
                        new
                        {
                            StudentId = "S1",
                            AssignmentId = 1,
                            Feedback = "Good work",
                            PointsEarned = 8m,
                            Status = 1
                        },
                        new
                        {
                            StudentId = "S2",
                            AssignmentId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("LMS.Models.StudentCourse", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = "S1",
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = "S2",
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = "S3",
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = "S4",
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = "S5",
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LMS.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "I1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e3ed75d-ef2a-4ab4-a3ef-6c17ae6a8b39",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 5, 983, DateTimeKind.Local).AddTicks(9042),
                            Email = "smith@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Smith",
                            NormalizedEmail = "SMITH@UNI.COM",
                            NormalizedUserName = "SMITH@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGmmZra/4lfuYoNmBDrqjzED1TOxPJnPuCaIQtZE2I83OdUjT/Nu8+96taT3kRoTaQ==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "768fc6fb-4896-4e89-b031-f4538d7017b6",
                            TwoFactorEnabled = false,
                            UserName = "smith@uni.com"
                        },
                        new
                        {
                            Id = "I2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f5968c9e-7c67-4cfb-84e9-87ab374b7145",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 36, DateTimeKind.Local).AddTicks(211),
                            Email = "johnson@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Johnson",
                            NormalizedEmail = "JOHNSON@UNI.COM",
                            NormalizedUserName = "JOHNSON@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBqR4EYb7xIbkNAXd1fnUBxSe2CJ91gANeZUlM9QC/sNK9cSxxldTa4Pwunrb9emjQ==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "9a0c99d0-d9b2-4d99-b47b-a803e581e27e",
                            TwoFactorEnabled = false,
                            UserName = "johnson@uni.com"
                        },
                        new
                        {
                            Id = "I3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "797031e4-30f6-4e22-b49a-452d0710267c",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 92, DateTimeKind.Local).AddTicks(7590),
                            Email = "lee@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Lee",
                            NormalizedEmail = "LEE@UNI.COM",
                            NormalizedUserName = "LEE@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC3G+wMUB59RAwFd95rZmyMfs8RuyvE2dfEjW7QnfJz+FmiRvYaGa6OrXimNKlbyCw==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "79ce6402-fc40-481f-aa34-6f320d7aee14",
                            TwoFactorEnabled = false,
                            UserName = "lee@uni.com"
                        },
                        new
                        {
                            Id = "S1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2d75da69-7ead-480c-9914-92187e4d063c",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 143, DateTimeKind.Local).AddTicks(5592),
                            Email = "student1@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 1",
                            NormalizedEmail = "STUDENT1@UNI.COM",
                            NormalizedUserName = "STUDENT1@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJlw9GMS9h/b4GwprgwEH6UvU57PEDHBgmnXv7d9FRHskUq/4ABWPKzgxVDpyfJygA==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "29981f8d-0752-47c1-9958-64535091a5ae",
                            TwoFactorEnabled = false,
                            UserName = "student1@uni.com"
                        },
                        new
                        {
                            Id = "S2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d0d3bfd-a186-42a6-aaf2-5ce816dcc134",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 195, DateTimeKind.Local).AddTicks(2866),
                            Email = "student2@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 2",
                            NormalizedEmail = "STUDENT2@UNI.COM",
                            NormalizedUserName = "STUDENT2@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECEn4GFdD/KFEJhFAEdkB5fpg2X465WFkiNz97S0PCydozzm6fJOOUUr5Fp6i0jpQg==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "26002a05-13a9-4a74-9c2a-674a87ac5bb6",
                            TwoFactorEnabled = false,
                            UserName = "student2@uni.com"
                        },
                        new
                        {
                            Id = "S3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c6fef8fd-6787-449d-972c-be44bbb35678",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 246, DateTimeKind.Local).AddTicks(6856),
                            Email = "student3@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 3",
                            NormalizedEmail = "STUDENT3@UNI.COM",
                            NormalizedUserName = "STUDENT3@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDLWorrj/l3VJ3d3VjL4viVAeECaFuqKy8UufVq7tJ2WkrDkOP7MpZjxyBvsXTCaYw==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "0eab4826-4d95-426c-8e4b-57b7ab533bf4",
                            TwoFactorEnabled = false,
                            UserName = "student3@uni.com"
                        },
                        new
                        {
                            Id = "S4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "97ca0052-31f4-4912-83cc-fdd2590cdec2",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 301, DateTimeKind.Local).AddTicks(671),
                            Email = "student4@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 4",
                            NormalizedEmail = "STUDENT4@UNI.COM",
                            NormalizedUserName = "STUDENT4@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECtSurK+1I6iB1bxxsCueC3AN2f5bjSzRMurWq3J+eG7SRjtv+LyLb+70qVyWvxKqw==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "c9924525-ee25-4bf7-9c48-faae44805956",
                            TwoFactorEnabled = false,
                            UserName = "student4@uni.com"
                        },
                        new
                        {
                            Id = "S5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5bc90bc9-7d48-49a3-8395-73bf3971e494",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 352, DateTimeKind.Local).AddTicks(5359),
                            Email = "student5@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 5",
                            NormalizedEmail = "STUDENT5@UNI.COM",
                            NormalizedUserName = "STUDENT5@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIaLowWn99gVpFg9DTAOAHhpayneu9utJoiWcCXkYAwvI4+o/lb+spAMq8FoybkXyQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "db86736e-5c03-4a50-be26-46f407986b3b",
                            TwoFactorEnabled = false,
                            UserName = "student5@uni.com"
                        },
                        new
                        {
                            Id = "S6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9aeb560a-9ac5-4b4e-9d99-6cb0686f3042",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 410, DateTimeKind.Local).AddTicks(6346),
                            Email = "student6@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 6",
                            NormalizedEmail = "STUDENT6@UNI.COM",
                            NormalizedUserName = "STUDENT6@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECZroKPvVqvtZowlUBNEz7aRsIpYLkM1V7oBRKcx9DhQjBi1looegEf/INDz6ngqhg==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "c52b9f04-6da7-4b2d-af5d-a0b71c0f72aa",
                            TwoFactorEnabled = false,
                            UserName = "student6@uni.com"
                        },
                        new
                        {
                            Id = "S7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "09e04d4a-8f66-4120-baad-b1af6629c018",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 488, DateTimeKind.Local).AddTicks(8979),
                            Email = "student7@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 7",
                            NormalizedEmail = "STUDENT7@UNI.COM",
                            NormalizedUserName = "STUDENT7@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIr0wJPFeyG96ZNHGEpOjqob03KJN9cYnBWQOVTZk2/Zgw1C2/IYQjtxrKBQfWzLKA==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "780ac610-fafd-4549-85be-ed683542ffde",
                            TwoFactorEnabled = false,
                            UserName = "student7@uni.com"
                        },
                        new
                        {
                            Id = "S8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e1648e1b-1f54-4804-8f5f-d871d4a3e335",
                            CreatedDate = new DateTime(2026, 4, 23, 12, 7, 6, 540, DateTimeKind.Local).AddTicks(2062),
                            Email = "student8@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 8",
                            NormalizedEmail = "STUDENT8@UNI.COM",
                            NormalizedUserName = "STUDENT8@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJJIIQnaDcg71vQIuGG0aBiDuLXS9yL7q8BcEvDn0RBt9eO7aZGX0Gymm/0JoRdshA==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "9ea6652d-0498-47b2-989b-4d8e4ec6bcc9",
                            TwoFactorEnabled = false,
                            UserName = "student8@uni.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMS.Models.Instructor", b =>
                {
                    b.HasBaseType("LMS.Models.User");

                    b.HasDiscriminator().HasValue("Instructor");
                });

            modelBuilder.Entity("LMS.Models.Student", b =>
                {
                    b.HasBaseType("LMS.Models.User");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.HasOne("LMS.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.HasOne("LMS.Models.User", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.Models.Instructor", null)
                        .WithMany("CourseNavigationProperty")
                        .HasForeignKey("InstructorId1");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("LMS.Models.StudentAssignment", b =>
                {
                    b.HasOne("LMS.Models.Assignment", "Assignment")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", "Student")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.Models.StudentCourse", b =>
                {
                    b.HasOne("LMS.Models.Course", "Course")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.Navigation("StudentAssignments");
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("StudentEnrollments");
                });

            modelBuilder.Entity("LMS.Models.User", b =>
                {
                    b.Navigation("AssignmentSubmissions");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LMS.Models.Instructor", b =>
                {
                    b.Navigation("CourseNavigationProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
