// <auto-generated />
using System;
using LMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Migrations
{
    [DbContext(typeof(LmsContext))]
    partial class LmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            DueDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPoints = 10,
                            Title = "Variables Assignment"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            DueDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxPoints = 25,
                            Title = "Linked List"
                        });
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InstructorId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxEnrollment")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("InstructorId1");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6259),
                            Credits = 3,
                            Description = "Basics of coding",
                            EndDate = new DateTime(2026, 8, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6235),
                            InstructorId = "I1",
                            MaxEnrollment = 30,
                            StartDate = new DateTime(2026, 4, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6222),
                            Title = "Introduction to Programming"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6278),
                            Credits = 3,
                            Description = "Advanced data handling",
                            EndDate = new DateTime(2026, 8, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6277),
                            InstructorId = "I2",
                            MaxEnrollment = 25,
                            StartDate = new DateTime(2026, 4, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6277),
                            Title = "Data Structures"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6280),
                            Credits = 3,
                            Description = "ASP.NET Core",
                            EndDate = new DateTime(2026, 8, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6280),
                            InstructorId = "I3",
                            MaxEnrollment = 20,
                            StartDate = new DateTime(2026, 4, 26, 16, 19, 1, 548, DateTimeKind.Local).AddTicks(6279),
                            Title = "Web Development"
                        });
                });

            modelBuilder.Entity("LMS.Models.StudentAssignment", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PointsEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "AssignmentId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("StudentAssignments");

                    b.HasData(
                        new
                        {
                            StudentId = "S1",
                            AssignmentId = 1,
                            Feedback = "Good work",
                            PointsEarned = 8m,
                            Status = 1
                        },
                        new
                        {
                            StudentId = "S2",
                            AssignmentId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("LMS.Models.StudentCourse", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = "S1",
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = "S2",
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = "S3",
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = "S4",
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = "S5",
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LMS.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "I1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e8ad6c3-37a8-4ea3-863f-a5b88a5b4616",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 0, 964, DateTimeKind.Local).AddTicks(4488),
                            Email = "smith@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Smith",
                            NormalizedEmail = "SMITH@UNI.COM",
                            NormalizedUserName = "SMITH@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ976yXXLwjMpuQQrHB8vDtBOPSSCwvyxvDJLmj9ank5CFxxs+zlycyeiSIDQ41tnw==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "3d66c328-b03b-4421-9546-44b2b7a361e7",
                            TwoFactorEnabled = false,
                            UserName = "smith@uni.com"
                        },
                        new
                        {
                            Id = "I2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "872b9afa-1bbc-4002-9dc8-6b3186985bfc",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 15, DateTimeKind.Local).AddTicks(6066),
                            Email = "johnson@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Johnson",
                            NormalizedEmail = "JOHNSON@UNI.COM",
                            NormalizedUserName = "JOHNSON@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEOsydHJAjikwXVQFrC0gfh9S4/RcwPRAZyvcyO3oGlV1NLFbBZ3RFWaOGjxbJSLiw==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "9b0cf5d8-7a23-4d98-aafb-089f75db6d58",
                            TwoFactorEnabled = false,
                            UserName = "johnson@uni.com"
                        },
                        new
                        {
                            Id = "I3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "438f078e-7255-4047-8997-ad63fa8eeeaa",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 66, DateTimeKind.Local).AddTicks(1139),
                            Email = "lee@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Lee",
                            NormalizedEmail = "LEE@UNI.COM",
                            NormalizedUserName = "LEE@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENbz2Q3W4oDH7jfVHfNrWQc7r6NLfS8cKfwrnpZLDZ1DiBzbCXM0/is+Cjpj97TfHw==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "e502365a-4a8b-42bd-85d9-05f01f424984",
                            TwoFactorEnabled = false,
                            UserName = "lee@uni.com"
                        },
                        new
                        {
                            Id = "S1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1cfbb3ca-f6d3-48ac-ba79-1d3a15e5bee0",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 116, DateTimeKind.Local).AddTicks(2527),
                            Email = "student1@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 1",
                            NormalizedEmail = "STUDENT1@UNI.COM",
                            NormalizedUserName = "STUDENT1@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENyzeaaQPCCziiwsWgecbXZ+2ZZBQ4YN3Q6VGIikucHYWIAcRelJ8vRH3T4Rm4Ur7Q==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "a0a2d1d7-a4b1-486e-88f0-dde774fcde6b",
                            TwoFactorEnabled = false,
                            UserName = "student1@uni.com"
                        },
                        new
                        {
                            Id = "S2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc40595d-44c3-41d9-b5fc-f609e95f82a6",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 179, DateTimeKind.Local).AddTicks(4981),
                            Email = "student2@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 2",
                            NormalizedEmail = "STUDENT2@UNI.COM",
                            NormalizedUserName = "STUDENT2@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDgHkFJJXXuinNbcFTXzU8FaJOxojf0PxK8SyiNLzj0mBqlGOocAmVep2TQtoSN8fA==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "748688c2-0a79-46dd-a319-997a38263018",
                            TwoFactorEnabled = false,
                            UserName = "student2@uni.com"
                        },
                        new
                        {
                            Id = "S3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "479aa6ea-6bbc-4daf-a98f-aa456f1a771c",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 233, DateTimeKind.Local).AddTicks(8322),
                            Email = "student3@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 3",
                            NormalizedEmail = "STUDENT3@UNI.COM",
                            NormalizedUserName = "STUDENT3@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJaK80c58E8r9xqZwHBni0KKWrD37zboQxfREkTM2jwmW0EoJeDpFJIG2hmFeXE/dA==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "b9596b8a-12d2-4db0-92de-c241b66e49fd",
                            TwoFactorEnabled = false,
                            UserName = "student3@uni.com"
                        },
                        new
                        {
                            Id = "S4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38e39728-fff4-4fe0-8501-f53348ddcf4f",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 285, DateTimeKind.Local).AddTicks(9560),
                            Email = "student4@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 4",
                            NormalizedEmail = "STUDENT4@UNI.COM",
                            NormalizedUserName = "STUDENT4@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEClENe/fWisHABxF51+y743/YTL0UzePZ7MHiwX79KCu+nwFY7Ybci48KE4wbunH/Q==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "a6d8914b-5add-48ff-87b9-3ecce5c23e43",
                            TwoFactorEnabled = false,
                            UserName = "student4@uni.com"
                        },
                        new
                        {
                            Id = "S5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1df3e09f-f19c-4a32-99e9-032611158210",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 336, DateTimeKind.Local).AddTicks(3046),
                            Email = "student5@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 5",
                            NormalizedEmail = "STUDENT5@UNI.COM",
                            NormalizedUserName = "STUDENT5@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMYb1nlPy91xVVE7+9yIBdzVnC0oKKGbmOvtjD9yY6GGEPKaxYSSrgfiaSwD7jh44w==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "292237d1-18a2-4259-9c90-13a02d70c170",
                            TwoFactorEnabled = false,
                            UserName = "student5@uni.com"
                        },
                        new
                        {
                            Id = "S6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fac3aea8-a19c-4d6b-a1ad-081fe8de12a7",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 389, DateTimeKind.Local).AddTicks(7153),
                            Email = "student6@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 6",
                            NormalizedEmail = "STUDENT6@UNI.COM",
                            NormalizedUserName = "STUDENT6@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENbholLHqZ51EAt/nlyO5NTc4sRLwdmxfdA2xoFdZbO8GpdjIVf9fo3bZpSTqnWM1Q==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "4084a422-4d8c-47a1-91e9-fce12a04e760",
                            TwoFactorEnabled = false,
                            UserName = "student6@uni.com"
                        },
                        new
                        {
                            Id = "S7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47c87be2-93fc-48dd-8c5c-40c68188266b",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 439, DateTimeKind.Local).AddTicks(9450),
                            Email = "student7@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 7",
                            NormalizedEmail = "STUDENT7@UNI.COM",
                            NormalizedUserName = "STUDENT7@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEAVWCE0FdpJq07MdQpR9v3nKaokfB4NTvyLoW+7j1deOJbR+3HpVcpJ5Xv3AAqiiQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "2f981060-b233-4b39-a053-beecce0d7515",
                            TwoFactorEnabled = false,
                            UserName = "student7@uni.com"
                        },
                        new
                        {
                            Id = "S8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ceace6cc-f514-4666-b48e-20bc666bd80e",
                            CreatedDate = new DateTime(2026, 4, 26, 16, 19, 1, 498, DateTimeKind.Local).AddTicks(6927),
                            Email = "student8@uni.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Student 8",
                            NormalizedEmail = "STUDENT8@UNI.COM",
                            NormalizedUserName = "STUDENT8@UNI.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDh15mK3yhXSZ+oAsH2S8Su/TG86LDw1ZbrOlqE4eMirK0ReD4tJEhL0S64x+23xTQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "f3db2bb6-a7b9-47af-b99f-e5186149530b",
                            TwoFactorEnabled = false,
                            UserName = "student8@uni.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "R1",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "R2",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "I1",
                            RoleId = "R1"
                        },
                        new
                        {
                            UserId = "I2",
                            RoleId = "R1"
                        },
                        new
                        {
                            UserId = "I3",
                            RoleId = "R1"
                        },
                        new
                        {
                            UserId = "S1",
                            RoleId = "R2"
                        },
                        new
                        {
                            UserId = "S2",
                            RoleId = "R2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LMS.Models.Instructor", b =>
                {
                    b.HasBaseType("LMS.Models.User");

                    b.HasDiscriminator().HasValue("Instructor");
                });

            modelBuilder.Entity("LMS.Models.Student", b =>
                {
                    b.HasBaseType("LMS.Models.User");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.HasOne("LMS.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.HasOne("LMS.Models.User", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.Models.Instructor", null)
                        .WithMany("CourseNavigationProperty")
                        .HasForeignKey("InstructorId1");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("LMS.Models.StudentAssignment", b =>
                {
                    b.HasOne("LMS.Models.Assignment", "Assignment")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", "Student")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.Models.StudentCourse", b =>
                {
                    b.HasOne("LMS.Models.Course", "Course")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LMS.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Models.Assignment", b =>
                {
                    b.Navigation("StudentAssignments");
                });

            modelBuilder.Entity("LMS.Models.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("StudentEnrollments");
                });

            modelBuilder.Entity("LMS.Models.User", b =>
                {
                    b.Navigation("AssignmentSubmissions");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LMS.Models.Instructor", b =>
                {
                    b.Navigation("CourseNavigationProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
